name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
  workflow_dispatch:
    inputs:
      environment:
        type: string
        default: main
        required: true
jobs:

  ci:
    name: Run CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23' ]
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Determine Go cache paths
        id: golang-path
        run: |
          echo "build=$(go env GOCACHE)" >>"$GITHUB_OUTPUT"
          echo "module=$(go env GOMODCACHE)" >>"$GITHUB_OUTPUT"
        shell: bash

      - name: Setup Go cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.golang-path.outputs.build }}
            ${{ steps.golang-path.outputs.module }}
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum', 'Makefile') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Run tests
        run: make ci
